<div class="flex min-h-screen">
    <aside class="relative hidden w-1/2 flex-col justify-between bg-primary-800 p-12 lg:flex xl:w-[55%]">
        <div class="pointer-events-none absolute inset-0 opacity-[0.07]"
             style="background-image: radial-gradient(circle at 1px 1px, #fff 1px, transparent 0); background-size: 28px 28px;"
             aria-hidden="true"></div>

        <div class="relative">
            <div class="flex items-center gap-3">
                <span class="grid h-11 w-11 place-items-center rounded-[12px] bg-accent-500 text-primary-950">
                    <x-icon name="truck" class="h-6 w-6" />
                </span>
                <span class="text-2xl font-semibold tracking-tight text-white">Microfleet</span>
            </div>

            <p class="mt-10 max-w-lg text-3xl font-semibold leading-snug tracking-tight text-white">
                Fleet and transportation operations, clearly managed
            </p>
            <p class="mt-4 max-w-md text-[15px] leading-relaxed text-primary-200">
                One focused subsystem for vehicles, reservations, dispatch, drivers, trips, fuel,
                route planning, and transportation cost control.
            </p>
        </div>

        <dl class="relative grid grid-cols-3 gap-6 border-t border-primary-700/60 pt-8">
            <div>
                <dt class="text-xs font-medium uppercase tracking-wider text-primary-300">Vehicles tracked</dt>
                <dd class="mt-1.5 text-2xl font-semibold tabular-nums text-white">25</dd>
            </div>
            <div>
                <dt class="text-xs font-medium uppercase tracking-wider text-primary-300">Monthly fuel spend</dt>
                <dd class="mt-1.5 text-2xl font-semibold tabular-nums text-white">PHP 428K</dd>
            </div>
            <div>
                <dt class="text-xs font-medium uppercase tracking-wider text-primary-300">Utilization rate</dt>
                <dd class="mt-1.5 text-2xl font-semibold tabular-nums text-white">78.5%</dd>
            </div>
        </dl>
    </aside>

    <main class="flex w-full flex-col justify-center px-6 py-12 sm:px-12 lg:w-1/2 xl:w-[45%]">
        <div class="mx-auto w-full max-w-sm">
            <div class="mb-8 flex items-center gap-2.5 lg:hidden">
                <span class="grid h-9 w-9 place-items-center rounded-[8px] bg-primary-600 text-white">
                    <x-icon name="truck" />
                </span>
                <span class="text-xl font-semibold tracking-tight text-neutral-900">Microfleet</span>
            </div>

            @if(session('status'))
                <div class="mb-5 flex items-center gap-2 rounded-[8px] border border-amber-300 bg-amber-50 px-3.5 py-2.5 text-xs text-amber-800">
                    <x-icon name="info" class="h-4 w-4 shrink-0 text-amber-600" />
                    <span>{{ session('status') }}</span>
                </div>
            @endif

            @if($requiresTwoFactor)
                {{-- 2FA Verification Challenge --}}
                <div class="rounded-[12px] border border-neutral-200 bg-white p-6 shadow-xs">
                    <div class="mb-5 flex items-center gap-3">
                        <div class="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-emerald-100 text-emerald-700">
                            <x-icon name="shield-check" class="h-5 w-5" />
                        </div>
                        <div>
                            <h1 class="text-lg font-semibold tracking-tight text-neutral-800">Two-Factor Authentication</h1>
                            <p class="text-xs text-neutral-500">Google Authenticator Verification</p>
                        </div>
                    </div>

                    <p class="text-xs text-neutral-600">
                        @if($usingRecoveryCode)
                            Enter one of your 9-character emergency backup recovery codes.
                        @else
                            Enter the 6-digit authentication code generated by your <strong>Google Authenticator</strong> app.
                        @endif
                    </p>

                    <form wire:submit="verifyTwoFactor" class="mt-5 space-y-4" novalidate>
                        <div>
                            @if($usingRecoveryCode)
                                <label for="twoFactorCode" class="block text-xs font-medium text-neutral-700">
                                    Recovery Code <span class="text-danger">*</span>
                                </label>
                                <input type="text"
                                       id="twoFactorCode"
                                       wire:model="twoFactorCode"
                                       autocomplete="one-time-code"
                                       placeholder="ABCD-1234"
                                       autofocus
                                       class="mt-1 block h-10 w-full rounded-[8px] border border-neutral-300 px-3 text-center font-mono text-base tracking-wider uppercase text-neutral-800 focus:border-primary-500 focus:outline-none focus:ring-2 focus:ring-primary-600/30 {{ $errors->has('twoFactorCode') ? 'border-danger focus:border-danger focus:ring-danger/25' : '' }}" />
                            @else
                                <label for="twoFactorCode" class="block text-xs font-medium text-neutral-700">
                                    6-Digit Code <span class="text-danger">*</span>
                                </label>
                                <input type="text"
                                       id="twoFactorCode"
                                       wire:model="twoFactorCode"
                                       maxlength="6"
                                       inputmode="numeric"
                                       autocomplete="one-time-code"
                                       placeholder="000000"
                                       autofocus
                                       class="mt-1 block h-11 w-full rounded-[8px] border border-neutral-300 px-3 text-center font-mono text-2xl tracking-[0.35em] text-neutral-800 focus:border-primary-500 focus:outline-none focus:ring-2 focus:ring-primary-600/30 {{ $errors->has('twoFactorCode') ? 'border-danger focus:border-danger focus:ring-danger/25' : '' }}" />
                            @endif

                            @error('twoFactorCode')
                                <p id="twoFactorCode-error" class="mt-1 flex items-start gap-1 text-xs text-danger">
                                    <x-icon name="alert-circle" class="mt-px h-3.5 w-3.5 shrink-0" />
                                    <span>{{ $message }}</span>
                                </p>
                            @enderror
                        </div>

                        <x-btn type="submit" variant="primary" size="lg" class="w-full" wire:loading.attr="disabled">
                            <span wire:loading.remove wire:target="verifyTwoFactor">Verify & Sign in</span>
                            <span wire:loading wire:target="verifyTwoFactor">Verifying...</span>
                        </x-btn>
                    </form>

                    <div class="mt-5 flex flex-col items-center gap-2.5 border-t border-neutral-200 pt-4 text-xs">
                        <button type="button"
                                wire:click="toggleRecoveryCode"
                                class="font-medium text-primary-700 hover:text-primary-800 hover:underline">
                            {{ $usingRecoveryCode ? 'Use Google Authenticator code instead' : 'Lost device? Use emergency recovery code' }}
                        </button>
                        <button type="button"
                                wire:click="cancelTwoFactor"
                                class="text-neutral-500 hover:text-neutral-700 hover:underline">
                            Cancel and return to sign in
                        </button>
                    </div>
                </div>

            @else
                {{-- Standard Login Form --}}
                <h1 class="text-2xl font-semibold tracking-tight text-neutral-800">Sign in</h1>
                <p class="mt-1 text-sm text-neutral-500">Use the account issued by your transport operations team.</p>

                <form wire:submit="authenticate" class="mt-8 space-y-5" novalidate>
                    <x-form-field
                        label="Email address"
                        name="email"
                        type="email"
                        id="email"
                        placeholder="you@microfleet.local"
                        :error="$errors->first('email')"
                        required
                        autocomplete="username"
                        wire:model="email" />

                    <div>
                        <div class="mb-1 flex items-baseline justify-between gap-2">
                            <label for="password" class="block text-[13px] font-medium text-neutral-700">
                                Password <span class="text-danger" aria-hidden="true">*</span>
                            </label>
                            <a href="#" class="text-[13px] font-medium text-primary-700 hover:text-primary-800 hover:underline">
                                Forgot password?
                            </a>
                        </div>

                        <div x-data="{ show: false }" class="relative">
                            <input id="password"
                                   :type="show ? 'text' : 'password'"
                                   wire:model="password"
                                   autocomplete="current-password"
                                   required
                                   @if($errors->has('password')) aria-invalid="true" aria-describedby="password-error" @endif
                                   class="block h-9 w-full rounded-[8px] border bg-white px-3 pr-10 text-sm text-neutral-800 placeholder:text-neutral-400 focus:outline-none focus:ring-2 {{ $errors->has('password') ? 'border-danger focus:border-danger focus:ring-danger/25' : 'border-neutral-300 focus:border-primary-500 focus:ring-primary-600/30' }}">

                            <button type="button"
                                    @click="show = !show"
                                    class="absolute inset-y-0 right-0 grid w-10 place-items-center text-neutral-500 hover:text-neutral-800"
                                    :aria-label="show ? 'Hide password' : 'Show password'">
                                <x-icon name="eye" />
                            </button>
                        </div>

                        @error('password')
                            <p id="password-error" class="mt-1 flex items-start gap-1 text-xs text-danger">
                                <x-icon name="alert-circle" class="mt-px h-3.5 w-3.5 shrink-0" />
                                <span>{{ $message }}</span>
                            </p>
                        @enderror
                    </div>

                    <div class="flex items-center gap-2">
                        <input id="remember" type="checkbox" wire:model="remember"
                               class="h-4 w-4 rounded-[4px] border-neutral-300 text-primary-600 focus:ring-2 focus:ring-primary-600/30">
                        <label for="remember" class="text-sm text-neutral-700">Remember me on this device</label>
                    </div>

                    <x-btn type="submit" variant="primary" size="lg" class="w-full" wire:loading.attr="disabled">
                        <span wire:loading.remove wire:target="authenticate">Sign in</span>
                        <span wire:loading wire:target="authenticate">Signing in...</span>
                    </x-btn>
                </form>


            @endif
        </div>
    </main>
</div>
