<div>
    <x-breadcrumb />

    <x-page-header
        title="Reports Center"
        subtitle="Standard regulatory and management reports. Open one to filter and export it.">
        <x-slot:actions>
            <x-btn icon="calendar">Scheduled reports</x-btn>
            <x-btn variant="primary" icon="plus">Build Custom Report</x-btn>
        </x-slot:actions>
    </x-page-header>

    <ul class="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">
        @foreach($cards as $card)
            <li>
                @php $href = isset($card['route']) ? route($card['route']) : '#'; @endphp
                <a href="{{ $href }}"
                   class="flex h-full flex-col rounded-[12px] border border-neutral-200 bg-white p-5 shadow-card transition-shadow hover:shadow-flyout">

                    <span class="grid h-10 w-10 shrink-0 place-items-center rounded-[8px] bg-primary-50 text-primary-700">
                        <x-icon :name="$card['icon']" class="h-5 w-5" />
                    </span>

                    <h2 class="mt-4 text-[15px] font-semibold text-neutral-800">{{ $card['title'] }}</h2>
                    <p class="mt-1 flex-1 text-[13px] leading-relaxed text-neutral-500">{{ $card['desc'] }}</p>

                    <span class="mt-4 inline-flex items-center gap-1.5 text-[13px] font-medium text-primary-700">
                        {{ isset($card['route']) ? 'Open report' : 'Configure' }}
                        <x-icon name="arrow-right" class="h-4 w-4" />
                    </span>
                </a>
            </li>
        @endforeach
    </ul>

    <div class="mt-5 grid grid-cols-1 gap-5 lg:grid-cols-3">
        <x-card class="lg:col-span-2" flush title="Recently generated"
                subtitle="Reports run across the cooperative in the last 7 days">
            <x-data-table sort-key="generated" sort-dir="desc" caption="Recently generated reports">
                <x-slot:head>
                    <x-th sort="report">Report</x-th>
                    <x-th sort="scope">Scope</x-th>
                    <x-th sort="by">Generated By</x-th>
                    <x-th sort="generated">Generated</x-th>
                    <x-th sort="format">Format</x-th>
                    <x-th align="right" sr-only>Actions</x-th>
                </x-slot:head>

                @foreach([
                    ['Portfolio at Risk', 'All branches · Aug 2026', 'Ramon B. Aguilar', '2026-09-08 16:20', 'XLSX'],
                    ['Collection Efficiency', 'Malolos Main · Aug 2026', 'Teresita G. Gonzales', '2026-09-08 09:41', 'PDF'],
                    ['Disbursement Summary', 'All branches · Q3 2026', 'Editha C. Ramirez', '2026-09-06 14:12', 'XLSX'],
                    ['Trial Balance', 'All branches · Aug 2026', 'Ramon B. Aguilar', '2026-09-05 11:33', 'PDF'],
                    ['Savings Movement', 'Sta. Maria · Aug 2026', 'Benigno L. Ocampo', '2026-09-04 17:05', 'XLSX'],
                ] as $i => [$report, $scope, $by, $generated, $format])
                    <tr data-row data-report="{{ $report }}" data-scope="{{ $scope }}" data-by="{{ $by }}"
                        data-generated="{{ $generated }}" data-format="{{ $format }}"
                        class="transition-colors hover:bg-primary-50 {{ $i % 2 ? 'bg-neutral-50' : '' }}">
                        <td data-label="Report" class="px-3 py-2.5 font-medium text-neutral-800">{{ $report }}</td>
                        <td data-label="Scope" class="px-3 py-2.5 text-neutral-600">{{ $scope }}</td>
                        <td data-label="Generated By" class="px-3 py-2.5 text-neutral-600">{{ $by }}</td>
                        <td data-label="Generated" class="px-3 py-2.5 tabular-nums text-neutral-600">{{ $generated }}</td>
                        <td data-label="Format" class="px-3 py-2.5"><x-status-badge status="Draft">{{ $format }}</x-status-badge></td>
                        <td data-label="" class="px-3 py-2.5 text-right">
                            <x-btn size="sm" icon="download">Download</x-btn>
                        </td>
                    </tr>
                @endforeach
            </x-data-table>
        </x-card>

        <x-card title="Scheduled Reports" subtitle="Delivered automatically by email">
            <ul class="space-y-3">
                @foreach([
                    ['Portfolio at Risk', 'Every Monday, 7:00 AM', 'Active'],
                    ['Collection Efficiency', 'Daily, 6:00 PM', 'Active'],
                    ['Trial Balance', 'Month-end, 8:00 AM', 'Active'],
                    ['Member Growth', 'Quarterly', 'Pending'],
                ] as [$name, $cadence, $status])
                    <li class="flex items-center gap-3 rounded-[8px] border border-neutral-200 p-3">
                        <span class="grid h-8 w-8 shrink-0 place-items-center rounded-[8px] bg-neutral-100 text-neutral-600">
                            <x-icon name="calendar" class="h-4 w-4" />
                        </span>
                        <div class="min-w-0 flex-1">
                            <p class="truncate text-[13px] font-medium text-neutral-800">{{ $name }}</p>
                            <p class="truncate text-xs text-neutral-500">{{ $cadence }}</p>
                        </div>
                        <x-status-badge :status="$status" />
                    </li>
                @endforeach
            </ul>
        </x-card>
    </div>
</div>
