@php
    use App\Support\Format;

    $trail = [
        ['label' => 'Administration', 'route' => 'admin.reports'],
        ['label' => 'Reports Center', 'route' => 'admin.reports'],
        ['label' => 'Portfolio at Risk'],
    ];

    $par30 = $buckets[2]['amount'] + $buckets[3]['amount'] + $buckets[4]['amount'];
@endphp

<div>
    <x-breadcrumb :trail="$trail" />

    <x-page-header
        title="Portfolio at Risk"
        subtitle="As of 09 Sep 2026 · all branches · generated by Teresita G. Gonzales"
        :back="route('admin.reports')"
        back-label="Reports Center">
        <x-slot:actions>
            <x-btn icon="printer">Print</x-btn>
            <x-btn icon="file-spreadsheet">Export to Excel</x-btn>
            <x-btn variant="primary" icon="download">Export to PDF</x-btn>
        </x-slot:actions>
    </x-page-header>

    <x-filter-bar :show-search="false" :export="false" date-range>
        <x-select label="Branch" :options="collect($branches)->pluck('name')->all()" placeholder="All branches" width="w-52" />
        <x-select label="Loan product" :options="['Sikap Micro Loan', 'Negosyo Plus', 'Pantawid Emergency Loan', 'Agri-Asenso Loan', 'Kabuhayan Group Loan']" placeholder="All products" width="w-48" />
        <x-select label="Aging basis" :options="['Days past due', 'Missed instalments']" width="w-44" />
        <x-btn icon="refresh-cw">Run report</x-btn>
    </x-filter-bar>

    {{-- Summary KPIs --}}
    <section aria-label="Report summary" class="mb-5 grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <x-stat-card label="Gross Loan Portfolio" :value="Format::pesoCompact($portfolio)" :delta="3.4" icon="wallet" />
        <x-stat-card label="Portfolio at Risk" :value="Format::pesoCompact($atRisk)" :delta="1.9" good-direction="down" icon="alert-triangle" />
        <x-stat-card label="PAR Ratio" :value="Format::percent($atRisk / $portfolio * 100)" :delta="0.6" good-direction="down" icon="percent"
                     hint="Policy ceiling 5.0%" />
        <x-stat-card label="PAR > 30 days" :value="Format::percent($par30 / $portfolio * 100)" :delta="0.8" good-direction="down" icon="clock" />
    </section>

    <div class="mb-5 grid grid-cols-1 gap-5 lg:grid-cols-3">
        <x-card class="lg:col-span-2" title="PAR by branch and aging bucket"
                subtitle="Outstanding balance at risk, stacked by days past due">
            <x-charts.par-by-branch />
        </x-card>

        <x-card flush title="Aging summary">
            <table class="w-full border-collapse text-sm">
                <caption class="sr-only">Portfolio at risk by aging bucket</caption>
                <thead class="bg-neutral-100">
                    <tr>
                        <th scope="col" class="px-4 py-2.5 text-left text-xs font-semibold uppercase tracking-wide text-neutral-600">Bucket</th>
                        <th scope="col" class="px-4 py-2.5 text-right text-xs font-semibold uppercase tracking-wide text-neutral-600">Amount</th>
                        <th scope="col" class="px-4 py-2.5 text-right text-xs font-semibold uppercase tracking-wide text-neutral-600">%</th>
                    </tr>
                </thead>
                <tbody class="divide-y divide-neutral-200">
                    @foreach($buckets as $i => $b)
                        <tr class="{{ $i % 2 ? 'bg-neutral-50' : '' }}">
                            <td class="px-4 py-2.5">
                                <span class="inline-flex items-center gap-2 text-neutral-700">
                                    <span class="h-2.5 w-2.5 shrink-0 rounded-[3px]" style="background-color: {{ $b['color'] }}" aria-hidden="true"></span>
                                    {{ $b['label'] }}
                                </span>
                                <span class="block pl-[18px] text-xs tabular-nums text-neutral-500">{{ number_format($b['accounts']) }} accounts</span>
                            </td>
                            <td class="px-4 py-2.5 text-right font-medium tabular-nums text-neutral-800">{{ Format::pesoCompact($b['amount']) }}</td>
                            <td class="px-4 py-2.5 text-right tabular-nums text-neutral-600">{{ Format::percent($b['amount'] / $portfolio * 100) }}</td>
                        </tr>
                    @endforeach
                </tbody>
                <tfoot class="border-t-2 border-neutral-300 bg-neutral-50">
                    <tr>
                        <td class="px-4 py-3 text-[13px] font-semibold text-neutral-700">Total</td>
                        <td class="px-4 py-3 text-right font-semibold tabular-nums text-neutral-900">{{ Format::pesoCompact($portfolio) }}</td>
                        <td class="px-4 py-3 text-right font-semibold tabular-nums text-neutral-900">100.0%</td>
                    </tr>
                </tfoot>
            </table>
        </x-card>
    </div>

    {{-- Branch detail --}}
    <x-card class="mb-5" flush title="Detail by branch" subtitle="Portfolio at risk broken down per branch">
        <x-data-table sort-key="par" sort-dir="desc" caption="Portfolio at risk by branch">
            <x-slot:head>
                <x-th sort="branch">Branch</x-th>
                <x-th sort="manager">Branch Manager</x-th>
                <x-th sort="members" align="right">Members</x-th>
                <x-th sort="portfolio" align="right">Gross Portfolio</x-th>
                <x-th sort="atrisk" align="right">At Risk</x-th>
                <x-th sort="par" align="right">PAR > 30</x-th>
                <x-th sort="health">Portfolio Health</x-th>
            </x-slot:head>

            @foreach($branches as $i => $b)
                @php $branchAtRisk = $b['portfolio'] * ($b['par30'] / 100) * 1.8; @endphp
                <tr data-row data-branch="{{ $b['name'] }}" data-manager="{{ $b['manager'] }}"
                    data-members="{{ $b['members'] }}" data-portfolio="{{ $b['portfolio'] }}"
                    data-atrisk="{{ $branchAtRisk }}" data-par="{{ $b['par30'] }}" data-health="{{ 100 - $b['par30'] }}"
                    class="transition-colors hover:bg-primary-50 {{ $i % 2 ? 'bg-neutral-50' : '' }}">

                    <td data-label="Branch" class="px-3 py-2.5">
                        <span class="block font-medium text-neutral-800">{{ $b['name'] }}</span>
                        <span class="block text-xs text-neutral-500">{{ $b['city'] }}</span>
                    </td>
                    <td data-label="Branch Manager" class="px-3 py-2.5 text-neutral-600">{{ $b['manager'] }}</td>
                    <td data-label="Members" class="px-3 py-2.5 text-right tabular-nums text-neutral-700">{{ number_format($b['members']) }}</td>
                    <td data-label="Gross Portfolio" class="px-3 py-2.5 text-right tabular-nums text-neutral-800">{{ Format::peso($b['portfolio']) }}</td>
                    <td data-label="At Risk" class="px-3 py-2.5 text-right font-medium tabular-nums text-danger">{{ Format::peso($branchAtRisk) }}</td>
                    <td data-label="PAR > 30" class="px-3 py-2.5 text-right font-semibold tabular-nums {{ $b['par30'] > 5 ? 'text-danger' : 'text-neutral-700' }}">
                        {{ Format::percent($b['par30']) }}
                    </td>
                    <td data-label="Portfolio Health" class="px-3 py-2.5">
                        <x-meter :value="100 - $b['par30']" :thresholds="[94, 96]" class="w-32" />
                    </td>
                </tr>
            @endforeach

            <x-slot:foot>
                <tr>
                    <td data-label="" class="px-3 py-2.5 text-[13px] font-semibold text-neutral-700">All branches</td>
                    <td data-label="" class="px-3 py-2.5"></td>
                    <td data-label="Members" class="px-3 py-2.5 text-right font-semibold tabular-nums text-neutral-900">{{ number_format(array_sum(array_column($branches, 'members'))) }}</td>
                    <td data-label="Gross Portfolio" class="px-3 py-2.5 text-right font-semibold tabular-nums text-neutral-900">{{ Format::peso(array_sum(array_column($branches, 'portfolio'))) }}</td>
                    <td data-label="At Risk" class="px-3 py-2.5 text-right font-semibold tabular-nums text-danger">{{ Format::peso($atRisk) }}</td>
                    <td data-label="PAR > 30" class="px-3 py-2.5 text-right font-semibold tabular-nums text-danger">{{ Format::percent($par30 / $portfolio * 100) }}</td>
                    <td data-label="" class="px-3 py-2.5"></td>
                </tr>
            </x-slot:foot>
        </x-data-table>
    </x-card>

    {{-- Account-level detail --}}
    <x-card flush title="Accounts at risk" subtitle="Individual accounts contributing to the PAR figure">
        <x-data-table sort-key="dpd" sort-dir="desc" caption="Loan accounts at risk">
            <x-slot:head>
                <x-th sort="loan">Loan ID</x-th>
                <x-th sort="member">Member</x-th>
                <x-th sort="center">Center</x-th>
                <x-th sort="officer">Officer</x-th>
                <x-th sort="outstanding" align="right">Outstanding</x-th>
                <x-th sort="overdue" align="right">Amount Overdue</x-th>
                <x-th sort="dpd" align="right">DPD</x-th>
                <x-th sort="bucket">Bucket</x-th>
            </x-slot:head>

            @foreach(array_slice($accounts, 0, 12) as $i => $a)
                <tr data-row data-loan="{{ $a['loan_id'] }}" data-member="{{ $a['member'] }}"
                    data-center="{{ $a['center'] }}" data-officer="{{ $a['officer'] }}"
                    data-outstanding="{{ $a['outstanding'] }}" data-overdue="{{ $a['amount_overdue'] }}"
                    data-dpd="{{ $a['dpd'] }}" data-bucket="{{ $a['bucket'] }}"
                    class="transition-colors hover:bg-primary-50 {{ $i % 2 ? 'bg-neutral-50' : '' }}">

                    <td data-label="Loan ID" class="px-3 py-2.5">
                        <a href="{{ route('loans.accounts.show', $a['loan_id']) }}"
                           class="tabular-nums text-primary-700 hover:underline">{{ $a['loan_id'] }}</a>
                    </td>
                    <td data-label="Member" class="px-3 py-2.5 text-neutral-700">{{ $a['member'] }}</td>
                    <td data-label="Center" class="px-3 py-2.5 text-neutral-600">{{ $a['center'] }}</td>
                    <td data-label="Officer" class="px-3 py-2.5 text-neutral-600">{{ $a['officer'] }}</td>
                    <td data-label="Outstanding" class="px-3 py-2.5 text-right tabular-nums text-neutral-800">{{ Format::peso($a['outstanding']) }}</td>
                    <td data-label="Amount Overdue" class="px-3 py-2.5 text-right font-medium tabular-nums text-danger">{{ Format::peso($a['amount_overdue']) }}</td>
                    <td data-label="DPD" class="px-3 py-2.5 text-right font-semibold tabular-nums text-danger">{{ $a['dpd'] }}</td>
                    <td data-label="Bucket" class="px-3 py-2.5 text-neutral-700">{{ $a['bucket'] }}</td>
                </tr>
            @endforeach
        </x-data-table>

        <x-pagination :from="1" :to="12" :total="434" :current="1" :per-page="12" />
    </x-card>

    <p class="mt-5 text-xs text-neutral-500">
        Prepared under BSP Circular guidelines on portfolio quality reporting for microfinance-oriented institutions.
        Figures are unaudited and reflect balances as of 09 Sep 2026, 08:00 AM.
    </p>
</div>
