<div>
    <x-breadcrumb />

    <x-page-header title="Logistics Reports" subtitle="Operational, cost, fuel, maintenance, and compliance reports for fleet operations.">
        <x-slot:actions>
            <x-btn icon="download" @click="$dispatch('open-modal', 'export-report')">Export</x-btn>
            @if($canScheduleReports)
                <x-btn variant="primary" icon="clipboard-check" @click="$dispatch('open-modal', 'schedule-report')">Schedule Report</x-btn>
            @endif
        </x-slot:actions>
    </x-page-header>

    <section class="mt-6 grid grid-cols-1 gap-4 lg:grid-cols-2 xl:grid-cols-3">
        @foreach($reports as $report)
            <x-card>
                <div class="flex items-start gap-3">
                    <span class="grid h-10 w-10 shrink-0 place-items-center rounded-[8px] bg-primary-50 text-primary-700">
                        <x-icon :name="$report['icon']" />
                    </span>
                    <div class="min-w-0 flex-1">
                        <h2 class="text-[15px] font-semibold text-neutral-800">{{ $report['title'] }}</h2>
                        <p class="mt-1 text-sm text-neutral-500">{{ $report['desc'] }}</p>
                        <div class="mt-4 flex flex-wrap gap-2">
                            <x-btn size="sm" icon="eye" :href="route($report['route'])">Open Source</x-btn>
                            <x-btn size="sm" icon="download" :href="route('intelligence.reports.export', $report['key'])">CSV</x-btn>
                            <x-btn size="sm" icon="file-text" @click="$dispatch('open-modal', 'export-report')">PDF</x-btn>
                        </div>
                    </div>
                </div>
            </x-card>
        @endforeach
    </section>

    <x-card class="mt-5" flush>
        <x-slot:title>Recently Generated</x-slot:title>
        <x-slot:subtitle>Reports prepared for fleet management and administrator review.</x-slot:subtitle>
        <x-data-table sort-key="generated" sort-dir="desc" caption="Recently generated logistics reports">
            <x-slot:head>
                <x-th sort="report">Report</x-th>
                <x-th sort="scope">Scope</x-th>
                <x-th sort="by">Generated By</x-th>
                <x-th sort="generated">Generated</x-th>
                <x-th sort="format">Format</x-th>
            </x-slot:head>
            @foreach($recentReports as $i => $row)
                <tr data-row data-report="{{ $row['report'] }}" data-scope="{{ $row['scope'] }}" data-by="{{ $row['by'] }}" data-generated="{{ $row['generated'] }}" data-format="{{ $row['format'] }}"
                    class="transition-colors hover:bg-primary-50 {{ $i % 2 ? 'bg-neutral-50' : '' }}">
                    <td data-label="Report" class="px-3 py-2.5 font-medium text-neutral-800">{{ $row['report'] }}</td>
                    <td data-label="Scope" class="px-3 py-2.5 text-neutral-600">{{ $row['scope'] }}</td>
                    <td data-label="Generated By" class="px-3 py-2.5 text-neutral-600">{{ $row['by'] }}</td>
                    <td data-label="Generated" class="px-3 py-2.5 tabular-nums text-neutral-600">{{ \App\Support\Format::dateTime($row['generated']) }}</td>
                    <td data-label="Format" class="px-3 py-2.5"><x-status-badge :status="$row['format']" tone="info" /></td>
                </tr>
            @endforeach
        </x-data-table>
    </x-card>

    @if($canScheduleReports)
        <x-modal name="schedule-report" title="Schedule Logistics Report" subtitle="Send recurring reports to fleet managers or administrators." icon="calendar">
            <div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
                <x-form-field label="Report" type="select" name="report" :options="collect($reports)->pluck('title')->all()" />
                <x-form-field label="Frequency" type="select" name="frequency" :options="['Daily', 'Weekly', 'Monthly']" />
                <x-form-field label="Recipient" name="recipient" value="manager@microfleet.local" />
                <x-form-field label="Start date" type="date" name="start" value="2026-09-23" />
            </div>
            <x-slot:footer>
                <x-btn @click="$dispatch('close-modal')">Cancel</x-btn>
                <x-btn variant="primary" icon="check" @click="$dispatch('close-modal')">Schedule</x-btn>
            </x-slot:footer>
        </x-modal>
    @endif

    <x-modal name="export-report" title="Export Report" subtitle="CSV downloads are live; PDF uses the printable report view." icon="download">
        <div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
            <x-form-field label="Report" type="select" name="report" :options="collect($reports)->pluck('title')->all()" />
            <x-form-field label="Format" type="select" name="format" :options="['CSV', 'PDF']" />
        </div>
        <div class="mt-4 rounded-[8px] border border-neutral-200 bg-neutral-50 p-3 text-sm text-neutral-600">
            Use each report card's CSV button for a generated export, or open the source screen and print to PDF.
        </div>
        <x-slot:footer>
            <x-btn @click="$dispatch('close-modal')">Cancel</x-btn>
            <x-btn variant="primary" icon="download" @click="$dispatch('close-modal')">Prepare Export</x-btn>
        </x-slot:footer>
    </x-modal>
</div>
