<div>
    <x-breadcrumb />

    <x-page-header
        title="Membership Reports"
        subtitle="Standard membership reports. Open one to filter, chart, and export it.">
        <x-slot:actions>
            <x-btn icon="calendar">Schedule report</x-btn>
            <x-btn variant="primary" icon="plus">Build Custom Report</x-btn>
        </x-slot:actions>
    </x-page-header>

    <ul class="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-3">
        @foreach($cards as $card)
            <li>
                <a href="{{ route('membership.reports.show', $card['key']) }}"
                   class="flex h-full flex-col rounded-[12px] border border-neutral-200 bg-white p-5 shadow-card transition-shadow hover:shadow-flyout">

                    <div class="flex items-start justify-between gap-3">
                        <span class="grid h-10 w-10 shrink-0 place-items-center rounded-[8px] bg-primary-50 text-primary-700">
                            <x-icon :name="$card['icon']" class="h-5 w-5" />
                        </span>
                        <span class="text-right">
                            <span class="block text-xl font-semibold tabular-nums text-neutral-900">{{ $card['value'] }}</span>
                            <span class="block text-xs text-neutral-500">{{ $card['meta'] }}</span>
                        </span>
                    </div>

                    <h2 class="mt-4 text-[15px] font-semibold text-neutral-800">{{ $card['title'] }}</h2>
                    <p class="mt-1 flex-1 text-[13px] leading-relaxed text-neutral-500">{{ $card['desc'] }}</p>

                    <span class="mt-4 inline-flex items-center gap-1.5 text-[13px] font-medium text-primary-700">
                        Open report
                        <x-icon name="arrow-right" class="h-4 w-4" />
                    </span>
                </a>
            </li>
        @endforeach
    </ul>

    <x-card class="mt-5" title="Recently generated" subtitle="Reports you or your branch ran in the last 7 days" flush>
        <x-data-table sort-key="generated" sort-dir="desc" caption="Recently generated membership reports">
            <x-slot:head>
                <x-th sort="report">Report</x-th>
                <x-th sort="period">Period</x-th>
                <x-th sort="by">Generated By</x-th>
                <x-th sort="generated">Generated</x-th>
                <x-th sort="format">Format</x-th>
                <x-th align="right" sr-only>Actions</x-th>
            </x-slot:head>

            @foreach([
                ['Member Growth', 'Jan–Sep 2026', 'Teresita G. Gonzales', '2026-09-08 16:20', 'XLSX'],
                ['Members by Center', 'Aug 2026', 'Arnel P. Bacani', '2026-09-07 09:12', 'PDF'],
                ['Dormant Members', 'As of 31 Aug 2026', 'Ramon B. Aguilar', '2026-09-05 14:47', 'XLSX'],
                ['New Members', 'Aug 2026', 'Grace M. Villamor', '2026-09-03 11:05', 'PDF'],
            ] as $i => [$report, $period, $by, $generated, $format])
                <tr data-row data-report="{{ $report }}" data-period="{{ $period }}" data-by="{{ $by }}"
                    data-generated="{{ $generated }}" data-format="{{ $format }}"
                    class="transition-colors hover:bg-primary-50 {{ $i % 2 ? 'bg-neutral-50' : '' }}">
                    <td data-label="Report" class="px-3 py-2.5 font-medium text-neutral-800">{{ $report }}</td>
                    <td data-label="Period" class="px-3 py-2.5 text-neutral-600">{{ $period }}</td>
                    <td data-label="Generated By" class="px-3 py-2.5 text-neutral-600">{{ $by }}</td>
                    <td data-label="Generated" class="px-3 py-2.5 tabular-nums text-neutral-600">{{ $generated }}</td>
                    <td data-label="Format" class="px-3 py-2.5"><x-status-badge status="Draft">{{ $format }}</x-status-badge></td>
                    <td data-label="" class="px-3 py-2.5 text-right">
                        <x-btn size="sm" icon="download">Download</x-btn>
                    </td>
                </tr>
            @endforeach
        </x-data-table>
    </x-card>
</div>
